name: budget_tracker
description: "budget trackng flutter app using bloc"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  uuid: ^4.4.2
  equatable: ^2.0.5
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  figma_squircle: ^0.5.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  smooth_page_indicator: ^1.2.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
